### ISSUE TITLE
Add a option to customize the tab

### ISSUE THREAD

**Issue by xan2622** [oormicreations/Seashells#1]
Hi.

Could you please add **an option** in the preferences of your add-on **to give the user the choice of the location of the tab** in the N panel? (in order to move the add-on from its own tab to a custom one).

Some users might want to place your add-on in the *Edit* or in the *Tool* tab... (or elsewhere).

The N panel clutter is a real issue that has been annoying Blender users for years. 
Here is a related topic: https://blender.community/c/rightclickselect/dzdbbc/ 

According to the number of votes, there are many people who don't like having many tabs vertically in the N panel. The only workaround is to add an option in the addon preferences.

This option is very convenient for the user, especially when there are many add-ons that add their own tab on the N panel (it could become overcrowded vertically). 

---

Maybe you could have a look at the source code of these (free) add-ons (to reuse the lines related to this feature)?

**Backface Hiding** :  https://gitlab.com/ChameleonScales/Backface_Hiding

![6cb58ec90d0eaf2859819909e32075473fcd9f47](https://user-images.githubusercontent.com/1732773/79038461-b7cce680-7bd9-11ea-8eb7-97311b8566ba.jpeg)

**SpeedRetopo** : https://gumroad.com/l/speedretopo

![1173cda700ee4af649f858070ca426f970587afb](https://user-images.githubusercontent.com/1732773/79038462-bc919a80-7bd9-11ea-9d6f-d518dd2f198e.jpeg)

Thank you in advance for considering to add this option.

**Comment by oormicreations** [comment]
Unfortunately there is no way to set the UI location before executing the addon itself. When it is executed, it is already present and will throw an error.
Secondly, when the addon is present in any other location except 3d view, it will not work as the context required for it to work is 3d view. It throws an error.
I could get the options drop down under installed addon and it saves the options.
You can edit the code to set it to a different location. The line number to edit is mentioned in the script.
If anyone is interesting in using it, the file is attached.

[Seashells012_Notworking.txt](https://github.com/oormicreations/Seashells/files/4523022/Seashells012_Notworking.txt)

**Comment by xan2622** [comment]
Hi. 

> Unfortunately there is no way to set the UI location before executing the addon itself. When it is executed, it is already present and will throw an error.

After being activated, the two addons above (**Backface Hiding** and **SpeedRetopo**) have their own tab displayed on the N panel by default. They both have the location of their tab is customizable in the addon preferences. When the user changes it, it stays forever in this new tab. 

I've been told that **they store this "String" variable in the _userpref.blend_ file.** 
I guess that they just reuse this information from this file the next time Blender is launched.

> Secondly, when the addon is present in any other location except 3d view, it will not work as the context required for it to work is 3d view. It throws an error.

There's no point of displaying the custom tab elsewhere than on the 3Dview, in the N panel.
